// # GCD(2 consecutive elements) is always 1

// # if num1 = a^k11 * b^k12 ... , and num1 = a^k12 * b^k22 ...
//      GCD = a^(min(k11, k12)) * b^(min(k12, k22)) ...
//      LCM = a^(max(k11, k12)) * b^(max(k12, k22)) ...

// # If a number is composite then it's either divisible by p*p for some prime p, or divisible by two distinct primes p and q
